### ISSUE TITLE
Add search/filter to project list page

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#2749]
For users with many projects an easy way to narrow down the list would be to provide a search function with filters the list to those with project names, descriptions, or other metadata which have substring matches with the user's input.

This could take the form of a simple text input field at the top of the page with the standard magnifying glass search icon.

**Comment by thadguidry** [comment]
### Adjustments
With subtle changes to the existing `projectTags` div and `ul#tagsUI` (removing margin, adjusting padding, etc. such as:

1. Create additional space for the magnifying glass icon.  Shifting `left` the existing `tagsUI` and small margin adjustment to `projectTags` to allow more vertical room perhaps:
```css
ul#tagsUl {
    margin: ;
    padding: 0;
    left: 60px;
}
``` 
```css
#projectTags {
    position: relative;
    padding: 3px 10px;
    margin: 0px;  //change to 0px from 5px
    font-size: 130%;
    border-radius: 5px;
    -moz-border-radius: 5px;
    -webkit-border-radius: 5px;
    background: #bcf;
    min-height: 18px;
    height: auto;
    overflow: auto;
}
```

2. Another `<div>` layer for `projectSearch` might be added for text input for the new search functionality. 

### Prototype visualization

Unclicked magnifying glass icon:

![Annotation 2020-06-17 152542](https://user-images.githubusercontent.com/986438/84949085-49614480-b0b2-11ea-89bf-7786b0b2b193.png)

Clicked magnifying glass icon (showing icon highlighted with background contrasting) with `projectSearch` text input box replacing the `projectTags` element:

![Annotation 2020-06-17 152543](https://user-images.githubusercontent.com/986438/84949503-f63bc180-b0b2-11ea-8a14-7f7dcbed6044.png)
