### ISSUE TITLE
Implement parallelization for Frontend tests

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3817]
Cypress tests are now taking an hour to run
Implement parallelization to speed up the cycle.

We are trying to tackle two issues here
* running time
* dependency to Cypress dashboard (because running cypress tests in parallel requires the dashboard)

### Investigation

I've tried
* Running Cypress tests on several machines, it's working, but requires the cypress dashboard
* Using a [non-official package to parallelize tests on the same machine](https://github.com/tnicola/cypress-parallel/issues) -> This is not working, unstable

### Proposed solution

We can add parallelization using the Cypress dashboard and the github matrix to spin-up several VMs

In order to mitigate the dependency to cypress dashboards (especially for forks), we can have the following configuration
```
name: Test CI

on: [push]
env:
  CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
jobs:
  prepare_ui_test_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: if [ -z "$CYPRESS_PROJECT_ID" ]; then echo "::set-output name=matrix::{\"browser\":[\"chrome\", \"edge\"], \"machines\":[1]}"; else echo "::set-output name=matrix::{\"browser\":[\"chrome\", \"edge\"], \"machines\":[1,2,3]}"; fi
  
  ui_test:
    needs: prepare_ui_test_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.prepare_ui_test_matrix.outputs.matrix)}}
    steps:
      - name: Cypress run
            uses: cypress-io/github-action@v2
            with:
              browser: ${{ matrix.browser }}
              working-directory: ./main/tests/cypress
              spec: |
                cypress/integration/open-project/*.spec.js
              wait-on: 'http://localhost:3333'
              record: ${{ $CYPRESS_RECORD_KEY != "" }}
              group: ${{ matrix.browser }}
              parallel: ${{ $CYPRESS_RECORD_KEY != "" }}
              ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
            env:
              CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
              CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
```
The issue is that we can't have several VMs without the Cypress dashboard, they would all run the entire test suite individually

In the proposed configuration, the matrix of machines becomes dynamic
* if no cypress key is present on the repository -> it will output a matrix of machines equals to [1], 1 Vm running all the tests
* if there is a cypress key in the repository 
     * then `parallel` and `record` flags are set to true
     * and the matrix for machines output [1,2,3], and 3 VMs will share the load
     
 Drawbacks:
  * the workflows becomes a bit difficult to read
  * we are still not sure that we're using 100% of the VM capabilities, but this is a problem for which I have no solution at the moment

### Alternative solution

We manually split the test suite in two or three jobs, each one of them sharing the `run_id`, so cypress dashboard can identify them as a single run
But the load balancing between test suites will be less effective than using the cypress dashboard.
