### ISSUE TITLE
Simplify the CI/CD workflows to use the builtin Maven cache feature in setup-java action that now supports it

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#5569]
We can now remove the actions/cache steps and replace them with a config setting under `setup-java` action.  It automatically uses actions/cache already under the hood and will create the fileHash for the Maven `**/pom.xml` automatically.
Documention: https://github.com/actions/setup-java/blob/main/README.md#caching-packages-dependencies

Usage such as:
```
steps:
- uses: actions/checkout@v3
- uses: actions/setup-java@v3
  with:
    distribution: 'temurin'
    java-version: '17'
    cache: 'maven'
- name: Build with Maven
  run: mvn -B package --file pom.xml
```

### To Reproduce
1. Run a PR workflow.

### Current Results
Extra steps not need for `actions/cache` separately.

### Expected Behavior
cleaner and less verbose build/test output in logs.
